alert("In This Programme I Am Going To Demonstrate Escape Sequence Charecter")
alert("One Example Of Escape Sequence Charecter Is New Line Charecter")
alert("In Order To Demonstrate It I Am Going To Declare Two String Varriables")
alert("What I Am Doing Is That I Am Giving Single Quote Using Escape Sequence Charecter")
alert("So Here Is The Final String Using Escape Sequence Charecter")
alert("Before Escape Sequence Charecter \" After Escape Sequence Charecter")