alert("In This Programme I Am Going To Demonstrate Some Important Methods Of Strings")
alert("Let's Start With A Method Which Returns The Length Of A String,In Order To Demonstrate This Method I Will Declare A String Varriable")
let str = prompt("Enter Any Kind Of Random String??")
alert("So The Length Of The String Declared Under The String Varriable Is " + str.length)
alert("Let's Make The String UpperCase")
alert("The UpperCase String Is " + str.toUpperCase())
alert("Let's Make The String LowerCase")
alert("The LowerCase String Is " + str.toLowerCase())
alert("Let's Slice The String We Declared Using Index")
alert("The Sliced String From Index 2 to The End Of The String", str.slice(2))
alert("We Are Going To Slice The String Again With An Ending Index")
alert("The Sliced String From Index 2 to Index 4", str.slice(2, 4))
alert("Now I Am Going To Replace A Part Of The String With Some Other Charecters")
alert("So The Replaced String Is " + str.replace("am", "i"))
alert("Now I Am Going To Demonstrate A String Method Which Trims Down The WhiteSpace From A String")
let White_Space_String = prompt("Enter A String With Some White Spaces??")
alert("So The String After Removing White Spaces Is " + White_Space_String.trim())
alert("Lastly I Want To Demonstrate Concatination Of String Using A Method Instead Of Addition Operator And For This I Am Going To Create Two More String Varriables")
let str_1 = prompt("Enter A String Before Concatination?")
let str_2 = prompt("Enter A String After Concatination?")
alert(str_1.concat(str_2))