alert("In This Programme I Am Going To Demonstrate About Some Basic Methods Of Arrays.")
alert("Firstly I Want To Demonstrate A Method Which Converts An Array To A String And For That I Am Going To Declare An Array.")
let Array = ["Harry Bhai", 8, true, false, 55.87]
alert("So I Declared An Array Which Is - " + Array)
alert("The String Representation Of Array I Declared Is - " + Array.toString() + " And I Am Printing The Type Of It For Surity That It Is A String - " + typeof Array.toString())
alert("Now I Am Going To Demonstrate A Method Which Also Make An Array Into String And Also Join Them With Something We Want To Provide.")
alert("I Am Going To Print The Array With After Using That Method - " + Array.join(" Joined Using A Method ") + " And Now I Am Going To Print The Type Of It After Using The Method - " + typeof Array.join(" Joined Using A Method "))
alert("Now I Am Going To Demonstrate A Method Which Adds A New Element At The End Of The Array And Returns The New Length Of The Array.")
let len = Array.push("Hello World", 0, true)
alert("So The New Array After Adding Values At The End Of It Is - " + Array + " And The Length Of The New Array Is - " + len)
alert("Now I Am Going To Demonstrate A Method Which Deletes An Element From The End Of An Array And Returns The Deleted Item.")
let Return = Array.pop()
alert("So The New Array After Deleting Values From The End Of It Is - " + Array + " And The Returned Item Is - " + Return)
alert("Now I Am Going To Demonstrate A Method Which Removes An Element From The Start Of An Array And Returns The Removed Item.")
let Return_2 = Array.shift()
alert("So The New Array After Removing Values From The Start Of It Is - " + Array + " And The Returned Item Is - " + Return_2)
alert("Now I Am Going To Demonstrate A Method Which Adds A New Element At The Start Of The Array And Returns The New Length Of The Array.")
let Len_2 = Array.unshift("Fuck You")
alert("So The New Array After Removing Values From The Start Of It Is - " + Array + " And The Length Of The New Array Is - " + Len_2)

