console.log("In This Programme I Am Going To Demonstrate Table And Some Methods Related To It.")
console.log("And In Order To Demonstrate It I Am Going To Use A Varriable.")
let table = document.documentElement.childNodes[2].firstElementChild.firstElementChild
console.log("So I Have Created A Varriable That Contains The HTML Table And I Am Printing The Table Rows Using That Varriable.")
console.log("Here Are The Table Rows")
console.log(table.rows)
console.log("Here Are The Cells Of One Table Row.")
console.log(table.rows[2].cells)
console.log("If A Caption Is Present On A Table Then The Below Method Will Show The Caption Of The Table.")
console.log(table.caption)
console.log("But In This Case There Is Not Any Caption Present In Table That's Why The Caption Method Is Returning 'NULL'")
console.log("Below Method Will Demonstrate If A Table Head Is Present In The Table")
console.log(table.tHead)
console.log("As You Can See That A Table Head Is Present In The Table That's Why The Above Property Is Returning 'tHead'")
console.log("Below Method Will Demonstrate If A Table Foot Is Present In The Table")
console.log(table.tFoot)
console.log("As You Can See That A Table Foot Is Not Present In The Table That's Why The Above Property Is Returning 'null'")
console.log("Below Method Will Demonstrate If A Table Body Is Present In The Table")
console.log(table.tBodies)
console.log("As You Can See That A Table Body Is Present In The Table That's Why The Above Property Is Returning 'tBody'")
console.log("Below Method Will Demonstrate On Which Row Index Currently You Are In.")
console.log(table.rows[0].rowIndex)
console.log("As You Can See That It Is Returning The Index Of The Row(On Which Row I Am Currently In).")
console.log("Below Method Will Demonstrate On Which Cell Index Currently You Are In.")
console.log(table.rows[0].cells[2].cellIndex)
console.log("As You Can See That It Is Returning The Index Of The Cell(On Which Cell I Am Currently In).")