alert("We Are Going To Create A String And Then We Are Going To Add A Number To It.")
let String = prompt("Enter A String??")
let Number = prompt("Enter A Number??")
prompt("So Here Is The Result ", String + Number)
alert("Now We Are Going To Find The Data Type Of The Result Of Previous Question")
prompt("So Here Is The Data Type Of The Result Which Is - ", typeof (String + Number))