console.log("In This Programme I Am Going To Demonstrate A Method Which Matches The CSS Selector After Getting The Element Using The Element ID.And In Order To Demonstrate It I Am Going To Use A Varriable.")
console.log("It Returns True If The CSS Selector Is Founded And False If The CSS Selector Is Not Founded")
let varriable = document.getElementById("Container")
console.log(varriable.matches(".container"))
console.log("Now I Am Going To Demonstrate A Method Which Shows If A CSS Selector Is Present In Parents Or In The Child As Well.And In Order To Demonstrate It I Am Going To Use An Another Varriable.")
let varriable_2 = document.getElementById("Box_1")
console.log(varriable_2.closest(".container"))
console.log("Now I Am Going To Demonstrate A Method Which Shows True If An Element Contains An Another Element And False If That Element Doesn't Contains The Another Element.And In Order To Demonstrate It I Am Going To Use A Varriable.")
let varriable_3 = document.getElementById("Box_1")
console.log(varriable_2.contains(varriable_3))