console.log("In This Programme I Am Going To Demonstrate Some Methods Of DOM Searching.")
console.log("Firstly I Am Going To Search A HTML Element With A Class.")
console.log(document.getElementsByClassName("Container"))
console.log("Then I Am Going To Search A HTML Element With A ID.")
console.log(document.getElementById("Division"))
console.log("Then I Am Going To Query All HTML Element With The Same Class.")
console.log(document.querySelectorAll(".box"))
console.log("Then I Am Going To Query Only First HTML Element With A Class.")
console.log(document.querySelector(".box"))
console.log("Now I Am Going To Query For An Element Using A Tag Name")
console.log(document.getElementsByTagName("a"))
console.log("Now I Am Going To Find An Element Using Name")
console.log(document.getElementsByName("Button"))