console.log("In This Programme I Am Going To Demonstrate Attribute Methods Of HTML")
console.log("Firstly I Want To Demonstrate A Method Which Shows True If A Particular Attribute Is Present In An HTML Element & False If That Particular Element Isn't Present In That HTML Element.")
console.log(document.getElementById("container").hasAttribute("name"))
console.log("Now I Am Going To Demonstrate A Method Which Gives The Value Of An Attribute.")
console.log(document.getElementById("container").getAttribute("class"))
console.log("Now I Am Going To Demonstrate A Method Which Set The Attribute Along With The Value Of A HTML Element.")
let a = document.querySelector(".box")
a.setAttribute("data-js", "Hey")
console.log(document.querySelector(`[data-js="Hey"]`))
console.log("So I Have Successfully Set A Custom Attribute And Make A Query With CSS Selector Which Is Returning The Element On Which I Set The Custom Attribute.")
console.log("Now I Am Going To Demonstrate A Method Which Delete An Attribute From A HTML Element.")
document.querySelectorAll(".box")[0].removeAttribute(`data-js`)
console.log("So As You Can See That The Attribute I Have Added A Moment Ago Has Now Been Deleted.")
console.log("Now I Am Going To Demonstrate A Method Which Gives All Of The Attributes From A HTML Element.")
console.log(document.getElementById("container").attributes)
console.log("Now I Am Going To Demonstrate A Method Which Only The Custom Attributes From A HTML Element.")
console.log(document.getElementById("container").dataset)
console.log("And I Can Access The Values Of Every Custom Attribute Using The Above Method.")
console.log(document.getElementById("container").dataset.one)
console.log("So That's How We All Can Able To Access Attributes Using DOM Manipulation.")
