console.log("In This Programme I Am Going To Demonstrate Class Name & Class List And Manipulating HTML File With These.")
console.log("Firstly I Am Going To Add A Class Using A Method.")
document.getElementsByClassName("Division")[0].classList.add("first")
console.log("As You Can See That A Class Has Been Added Which Is Already Designed With CSS That's Why The Division Is Visible Now.")
console.log("Now I Am Going To Remove The Class I Added Using A Method Too.")
document.getElementsByClassName("Division")[0].classList.remove("first")
console.log("As You Can See That The Class I Added Has Been Invisible Now Because I Removed It.")
console.log("I Can Also Replace A Class Using A Different Method Let's Demonstrate It.")
document.getElementsByClassName("Division")[0].className = "first"
console.log("As You Can See That The Class Which Was Removed Has Been Added Again With A Replacement Of The Class With Which I Was Finding The Division Which Is Already Designed With CSS That's Why The Division Is Visible Now.")
console.log("I Can Also See The Classes Using A Method.")
console.log(document.getElementsByClassName("first")[0].classList)
console.log("I Can Also Have A Boolean Value Using A Method Which Will Determine If A Class Is Present In The Element Or Not.")
console.log(document.getElementsByClassName("first")[0].classList.contains("first"))
console.log("Lastly I Want To Demonstrate A Method Whill Will Adds A Class If It Not Present In The Selected Element & Removes A Class If It Is Present In The Selected Element.")
console.log(document.getElementById("Div").classList.toggle("first"))
console.log("So It Is Returning False Because The Class Is Removed Which Was Present In The Element That's Why The Division Isn't Visible Anymore Which Was Desgined Using CSS.")