console.log("In This Programme I Am Going To Demonstrate Some Methods Which Will Add Some HTML Into An Element.")
console.log("Firstly I Am Going To Add A HTML Before End Of The Container Division.")
document.getElementById("container").insertAdjacentHTML("beforeend", '<h1>This Is A Text Entered Before The End Of The Container</h1>')
console.log("Now I Am Going To Add A HTML Before Begin Of The Box Division Under Container Division.")
document.getElementsByClassName("box")[0].insertAdjacentHTML("beforebegin", '<h1>This Is A Text Entered Before Begin Of The Box Division Under Container Division</h1>')
console.log("Now I Am Going To Add A HTML After Begin Of The Container Division.")
document.getElementsByClassName("Container")[0].insertAdjacentHTML("afterbegin", '<h1>This Is A Text Entered After The Begin Of The Container</h1>')
console.log("Now I Am Going To Add A HTML After End Of The Container Division.")
document.getElementsByClassName("box")[0].insertAdjacentHTML("afterend", '<h1>This Is A Text Entered After End Of The Box Division Under Container Division</h1>')
console.log("So That's How I Can Add Things Before And Ending Of The Division.")
console.log("Lastly I Want To Demonstrate A Method Which Remove The Node Which Has Made For Removal.")
document.getElementsByClassName("remove")[0].remove()
console.log("So That's How We Can Remove Any Type Of Node By Selecting It.")
